### PR TITLE
Topic/psc webpack plugin

### PR DESCRIPTION
**Pull request by ethul**
@natefaubion I've been working on a way to potentially leverage `psc-bundle`. I've followed the example code you provided (thanks again for working on this) and split up the loader into a loader and a separate plugin (https://github.com/ethul/purescript-webpack-plugin). If you have a chance to take a look, I'd appreciate any suggestions or feedback you might have.

### CODE REVIEW

**Comment by natefaubion** [comment]
Sure, I'll try to take a look at it some time this weekend.

**Comment by ethul** [comment]
Great. Thanks!

**Comment by natefaubion** [comment]
A couple of questions:

* Is a loader necessary at this point? The loader doesn't really "transform" source, as it just returns a single `require` call, so chaining loaders is practically useless. You should be able to just do all this in the plugin instead of deferring to a loader.
* Does the `bundleEntries` hook work well in the presence of multiple, disjoint entries as well as while watching. You are tracking it via `normal-module-factory`, so does this get added each time a watch is invoked? I don't really remember the exact steps webpack goes through. That was the biggest problem I had, I think. I couldn't quite get the ordering right automatically, and it was easy to trick it based on different dependency topologies.

**Comment by ethul** [comment]
@natefaubion Thanks for taking a look!

Indeed the loader is not doing much. I had originally attempted to omit the loader and just go with a plugin. However, I didn't see an appropriate async hook to run `psc` and `psc-bundle`. The loader provides a handy point to run this step. So that is really the only thing keeping me from going plugin-only. If we find the right hook we might be able to do away with the loader.

Regarding the `normal-module-factory`, the `before-resolve` runs each time a watch is invoked, which populates the `bundleEntries`. This approach seems to be working in my testing so far. Did you have a specific example in mind? I can try it out to see if this is working as expected.

**Comment by natefaubion** [comment]
I have a chunk of commented out code in one of my experiments:
```js
  compiler.plugin('normal-module-factory', function(nmf) {
    nmf.plugin('after-resolve', function(data, callback) {
      if (data.resource.match(/\.purs$/) && data.resource.indexOf('!') === -1) {
        data.loaders = [__filename]
      }
      callback(null, data)
    })
  })
```

What it does is add an implicit `purs-loader` to the file if it ends in `.purs`, so you don't have to specify it in your config. It doesn't remove the need for a loader, but the user doesn't have to know about it. I don't know if there's a reason why I commented it out :P

As far as the `bundleEntries` resolution goes, If you have something like this in a file:
```js
var foo = require('src/Foo.purs')
var bar = require('src/Bar.purs')
```

It should work fine. However if you do something like:
```js
var foo = require('src/Foo.purs')
var bar = require('./somewhere/else/bar.js')
```

Where `bar` has some arbitrary transitive dependency on a different `purs` file, then you'll probably have to start compilation for `foo` before that transitive dependency has even been resolved. As far as I know, there's no easy way to figure out all your `purs` entries first, and then do compilation at some later point.

**Comment by ethul** [comment]
@natefaubion I've updated the example. Does this cover the case you have in mind?

If so, then I think this works. The plugin uses the loader to hook into when the first purescript file is required and then runs `psc` and `psc-bundle` once for the webpack compilation. All of the `-m` module values `psc-bundle` should be gathered in the `before-resolve` step. The necessary purescript is compiled and bundled on the first required purescript file.

Let me know if I can clarify how this is working further, or maybe I don't have the right use-case in mind.

Regarding the code that implicitly adds the `purs-loader`, I will give that a go. Thanks for the example. It would be handy if the user only had to specify the plugin in their config.

**Comment by natefaubion** [comment]
Does doing this in `before-resolve` where you only have access to the request mean that you _must_ require the file with a `.purs` extension?

**Comment by ethul** [comment]
I will give it a try without the extension, but I think using
"data.request" mirrors the require statement. There may be an alternative
to determine if the file is a purescript file. However, I am okay with
indicating this as a limitation until a better solution is determined.

**Comment by ethul** [comment]
I gave it a quick test. Using `before-resolve` does mean that we'd need to require the file with a `.purs` extension. I am thinking this can either be a known limitation or maybe there is a better way to obtain this information.

**Comment by natefaubion** [comment]
What is the importance of using `before-resolve` instead of `after-resolve`?

**Comment by ethul** [comment]
Good question. Thank you for pointing out the `after-resolve` hook.

I recall testing this in an earlier attempt of the plugin and had thought that it was being invoked too late. However, after trying it with the current iteration of the plugin, it seems to work just fine. Plus it has the added benefit that we get the actual file path, so whether the user requires a purescript file with `.purs`, or without an extension, we can still detect the file appropriately.

I will make the change on the plugin to use this hook. I think this works out nicely.

**Comment by ethul** [comment]
@natefaubion Thanks again for all of your input on this PR. I am thinking these changes are a pretty good direction to go for the loader. Do you have any additional thoughts on this before I merge things in?

**Comment by osener** [comment]
This PR seems to introduce a new problem:

```purs
module Types where

data Bool = False | True

myTrue = True
```
```purs
module Lib where

import Types

bar True = true
bar _ = false
```
``` js
import {myTrue} from './Types.purs'
import {bar} from './Lib.purs'

console.log(bar(myTrue))  // false
```

**Comment by ethul** [comment]
Thanks for the example. I will take a look.

**Comment by osener** [comment]
These are the changes I made to my webpack config to use this branch, in case this is a configuration problem:

```diff
diff --git a/package.json b/package.json
index ade28f2..3a1a03d 100644
--- a/package.json
+++ b/package.json
@@ -47,7 +47,7 @@
     "eventsource-polyfill": "^0.9.6",
     "express": "^4.13.3",
     "purescript-webpack-plugin": "^0.1.1",
-    "purs-loader": "^0.4.0",
+    "purs-loader": "file:../purs-loader",
     "redux-devtools": "^3.0.1",
     "redux-devtools-dock-monitor": "^1.0.1",
     "redux-devtools-log-monitor": "^1.0.1",
diff --git a/webpack.config.dev.js b/webpack.config.dev.js
index 3de5200..d3da241 100644
--- a/webpack.config.dev.js
+++ b/webpack.config.dev.js
@@ -1,8 +1,9 @@
 var path = require('path');
 var webpack = require('webpack');
 
-var srcs = ['src[]=bower_components/purescript-*/src/**/*.purs', 'src[]=src/**/*.purs'];
-var ffis = ['ffi[]=bower_components/purescript-*/src/**/*.js'];
+var PurescriptWebpackPlugin = require('purescript-webpack-plugin');
+var src = ['bower_components/purescript-*/src/**/*.purs', 'src/**/*.purs'];
+var ffi = ['bower_components/purescript-*/src/**/*.js', 'src/**/*FFI.js'];
 
 module.exports = {
   devtool: 'cheap-module-eval-source-map',
@@ -19,10 +20,11 @@ module.exports = {
   plugins: [
     new webpack.HotModuleReplacementPlugin(),
     new webpack.NoErrorsPlugin(),
+    new PurescriptWebpackPlugin({ src, ffi })
   ],
   resolve: {
     extensions: ['', '.js', '.jsx', '.purs'],
-    modulesDirectories: ['node_modules', 'output']
+    modulesDirectories: ['node_modules', 'bower_components', 'output']
   },
   module: {
     loaders: [{
@@ -31,7 +33,7 @@ module.exports = {
       include: path.join(__dirname, 'src')
     }, {
       test: /\.purs$/,
-      loaders: ['purs-loader?output=output&' + srcs.concat(ffis).join('&')]
+      loaders: ['purs-loader']
     }]
   }
 };
```

**Comment by ethul** [comment]
Thanks for the config. I don't think you need 'output' in the
modulesDirectories. Can you do a quick test without that? Might not make a
difference though, but worth a try.

**Comment by osener** [comment]
@ethul Without that I'm getting a bunch of "Cannot resolve module" errors

```
ERROR in ./output/bundle.js
Module not found: Error: Cannot resolve module 'Prelude' in /home/ozan/vcs/webpack-test/output
 @ ./output/bundle.js 6:16-34 97:16-34

ERROR in ./output/bundle.js
Module not found: Error: Cannot resolve module 'Data.Maybe' in /home/ozan/vcs/webpack-test/output
 @ ./output/bundle.js 98:19-40

ERROR in ./output/bundle.js
Module not found: Error: Cannot resolve module 'Data.Nullable' in /home/ozan/vcs/webpack-test/output
 @ ./output/bundle.js 99:22-46

ERROR in ./output/bundle.js
Module not found: Error: Cannot resolve module 'Data.Function' in /home/ozan/vcs/webpack-test/output
 @ ./output/bundle.js 100:22-46

ERROR in ./output/bundle.js
Module not found: Error: Cannot resolve module 'Data.Tuple' in /home/ozan/vcs/webpack-test/output
 @ ./output/bundle.js 101:19-40

ERROR in ./output/bundle.js
Module not found: Error: Cannot resolve module 'Data.Array' in /home/ozan/vcs/webpack-test/output
 @ ./output/bundle.js 102:19-40

ERROR in ./output/bundle.js
Module not found: Error: Cannot resolve module 'Data.Foldable' in /home/ozan/vcs/webpack-test/output
 @ ./output/bundle.js 103:22-46

ERROR in ./output/bundle.js
Module not found: Error: Cannot resolve module 'Unsafe.Coerce' in /home/ozan/vcs/webpack-test/output
 @ ./output/bundle.js 104:22-46

ERROR in ./output/bundle.js
Module not found: Error: Cannot resolve module 'Actions' in /home/ozan/vcs/webpack-test/output
 @ ./output/bundle.js 105:16-34
```

**Comment by ethul** [comment]
Can you please try to totally remove your compiled purescript output and
build again?

**Comment by osener** [comment]
@ethul This fixed it, thanks! 

The culprit was the syntax checker plugin for my editor, it was calling `psc -o <project_root>/output` and breaking webpack build.

**Comment by ethul** [comment]
Great! Note that purescript/purescript#1794 may impact your code. I am
waiting for that fox before I merge this branch.

**Comment by osener** [comment]
I'm calling PS modules from JS modules so I've yet to hit that but thanks for the heads up.

Also, thanks for your work on purs-loader, it is already an invaluable part of my workflow!

**Comment by ethul** [comment]
Very welcome! And thanks for checking out the purs-loader and for your
testing. I hope to get all of these changes merged in soon!

**Comment by ethul** [comment]
Update: purescript/purescript#1794 has been resolved and looks to be included in purescript 0.8

**Pull request merged**
