### PR TITLE
Support ES modules

### PR DESCRIPTION
**Pull request by kl0tl**
This PR slightly adjusts the regexps used to rewrite require paths in modules read from the output directory so it supports both CJS and ES modules, in anticipation of https://github.com/purescript/purescript/pull/3791.

### CODE REVIEW

**Comment by cariandrum22** [comment]
PureScript 0.15 has been released and the module system used in the output JavaScript has been changed from CommonJS to ES Modules.

I was wondering if you could this PR could be merged.

**Comment by andys8** [comment]
I tried this change and it seems to make `purs-loader` work with PureScript v0.15

**Comment by andys8** [comment]
@ethul In case you read this: Are you open to merge or add maintainers to this repository or would you rather prefer a fork being published on npm? :)

**Comment by oguimbal** [comment]
+1 !

... I came up with exactly the same fix, and was about to submit a PR until I found this one :)

**Comment by ethul** [comment]
Thanks for the reminder for this. I have fallen a bit behind on PRs, but I
will take a look—apologies for the delay!

**Pull request merged**
