### PR TITLE
Refactor to compile independently of purescript-webpack-plugin.

### PR DESCRIPTION
**Pull request by alexmingoia**
In my quest to fix the double-compilation during hot-reloading, I ended up with a rewrite of the loader that accomplishes a number of things:

- Removes dependence on purescript-webpack-plugin, only the loader is needed
- Fixes double-compilation issue by loading compiled JS instead of adding
  `require()`.
- Uses `psc-ide-server` for fast rebuilds.
- Retains all the previous feature of purescript-webpack-plugin and purs-loader

Since it is a complete rewrite, I was going to release it as a separate module `purescript-loader`, but I thought it might be better if there was less fragmentation and it could be the next version of `purs-loader` instead - and `purescript-webpack-plugin` could be deprecated. I know some people will be butthurt by the fact that it's not written in PureScript...

### CODE REVIEW

**Comment by ethul** [comment]
Thanks for all of your work on this PR.

I think it is great that it hooks up with `psc-ide-server`, and having just the loader does simplify the setup a bit, which is nice.

Have you had a chance to give this version a go on the [`purescript-webpack-example`](https://github.com/ethul/purescript-webpack-example)?

**Comment by alexmingoia** [comment]
I'll make a branch to test with `purescript-webpack-example` tonight

**Comment by ethul** [comment]
Thanks!

**Comment by alexmingoia** [comment]
You can see it working with `purescript-webpack-example` here: https://github.com/alexmingoia/purescript-webpack-example/tree/topic/refactor

Note, I've disabled rebuilds with psc-ide behind the `pscIde: false` flag by default because I ran into a bug with `psc-ide`. It looks like it still has some rough edges, but as those get ironed out it could be changed to on by default.

**Comment by ethul** [comment]
Great. Thanks for updating the example.

Can you elaborate on the issue that you found? Are you referring to purescript/purescript#2123 or something else?

The refactored loader works well in the example. However, I did notice one odd case where the warnings are not displayed in the browser with hot reloading enabled. I found that the warnings were immediately cleared (before you can read them) when you have a compiler error and then save the file to fix the error. I don't see this as a huge deal, but thought it was worth mentioning.

Also, if we go ahead with the merge, are you open to a separate PR that maps this over to PureScript? I think it might be a nice-to-have at some point in the future. I'd be happy to make this update, unless you were keen on doing it.

**Comment by alexmingoia** [comment]
Correct, I was referring to purescript/purescript#2123.

Could you be more specific on how to reproduce the warnings issue? I'm pretty sure it's passing through all warnings and errors to webpack that come from the compiler. There's a related issue with `purescript-webpack-example`, which is that hot updates aren't accepted in `entry.js` and so cannot be correctly applied (requiring a reload). I'll push a change for that. Also, warnings from webpack compilation won't show up in the console if there was no actual change to the compiled JS output. This happens when there are warnings for a successful recompile where only type annotation changed (so JS output remains unchanged). Webpack doesn't see anything changed due to caching so the warnings don't go anywhere.

**Comment by ethul** [comment]
To reproduce the warning issue:

1. `npm run webpack:server:debug`

2. Load up `http://localhost:4008` in the browser

3. Remove the type declaration for [`foo`](https://github.com/alexmingoia/purescript-webpack-example/blob/0132cddc294cf98d590ac1d08c1824b52771a60f/src/Example/Foo.purs#L7).

4. Remove the end quotation mark for the value of [`foo`](https://github.com/alexmingoia/purescript-webpack-example/blob/0132cddc294cf98d590ac1d08c1824b52771a60f/src/Example/Foo.purs#L8). `foo = "A"` becomes `foo = "A`. This should show a compiler error in the browser's console.

4. Add back the end quotation mark for foo so that things compile correctly. At this point, I expected to see a warning of `MissingTypeDeclaration` upon the successful compile, but the browser console seems to show the warning and then immediately clear it.

Let me know if this reproduces it for you. And sounds good on mapping over to PureScript.

**Comment by alexmingoia** [comment]
The warnings is being passed to webpack, and it is being logged to the console. However, it appears that once an error has occurred, the subsequent HMR update for successful compilation does log the compilation warning, but then the HMR update isn't valid/can't be applied for whatever reason and webpack-dev-server is setup to reload the page in that scenario. So if you persist your console logs across page loads you'll see that the warning does show up but that the HMR code reloads the page because it can't apply the update.

**Comment by ethul** [comment]
Agreed that persisting the console logs looks to be the way to go here. I am unsure either what the loader could do about this. Thanks for digging into the issue.

I think this looks good to merge, unless you want to add any more commits. I did notice that rebuilding does not occur when the FFI is changed (with pscIde: false), but maybe we can just note this down and add the feature later on.

Also, I don't think we need the babelified source checked it. I could generate it on prepublish if that works for you.

**Comment by alexmingoia** [comment]
I fixed the FFI issue and removed the babelified source in favor of a prepublish script. It should be good to go 👍

**Comment by ethul** [comment]
Great! I will merge and publish this tonight. Thank you for all of your
work on this PR.

**Comment by ethul** [comment]
The new version is published under the `next` npm tag and can be installed with:

```bash
npm install purs-loader@next --save-dev
```

I will write up release notes and bring it over to the `latest` npm tag soon. I want to first update the `purescript-webpack-example`, deprecate the plugin, and do a little more testing.

But everything looks great! Thanks again for this update.

**Pull request merged**
