### PR TITLE
Configuration has an unknown property 'purescriptLoaderCache' #103

### PR DESCRIPTION
**Pull request by futpib**

### CODE REVIEW

**Comment by futpib** [comment]
I have not tested this yet though (after extracting class to a separate file).

**Comment by futpib** [comment]
Do you mind if I slip in some tests? I'd add [ava](https://github.com/avajs/ava) if that's fine.

**Comment by ethul** [comment]
Thanks! And adding some tests sounds great.

**Comment by cyrilfretlink** [comment]
Shouldn’t this be closed since https://github.com/ethul/purs-loader/pull/109 was merged instead?

**Comment by ethul** [comment]
@cyrilfretlink Yes. This should likely be closed. I liked the weak map implementation and the idea of tests in this PR, but we can always reopen it. Thanks.

**Pull request closed without merging**
