### PR TITLE
Add troubleshooting "Error spawn ENOENT"

### PR DESCRIPTION
**Pull request by cyrbon**

### CODE REVIEW

**Comment by ethul** [comment]
Looks great! Thanks.

Two small points:

 - Can you please update "then you need to ensure" to "then ensure".

 - Can you please update "If you use `npm run` and `npm start` on NixOS" to "If you run webpack through an npm script (e.g., `npm run` or `npm start`) on NixOS"

Do these sound okay to you?

**Comment by ethul** [comment]
Looks great!

**Comment by cyrbon** [comment]
Yeah that's much better, that's for the suggestion.

**Comment by ethul** [comment]
Thank you!

**Pull request merged**
